### ISSUE TITLE
Impossible to fetch packet with pypi

### ISSUE THREAD

**Issue by henri9813** [dinoboff/skeleton#5]
Hello

Here is the result of ```pip install skeleton```

```
PS C:\Users\henri\PycharmProjects> pip install skeleton
Collecting skeleton
  Downloading https://files.pythonhosted.org/packages/b2/e7/1e55141ec76bd6f29b8b4a216112c8f1bc1d41375f427bc98c6098174b39/skeleton-0.6.tar.gz (61kB)
    100% |████████████████████████████████| 71kB 833kB/s
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.10.tar.gz
    Traceback (most recent call last):
      File "C:\Users\henri\AppData\Local\Temp\pip-install-vf6fwa3c\skeleton\distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\henri\AppData\Local\Temp\pip-install-vf6fwa3c\skeleton\setup.py", line 5, in <module>
        distribute_setup.use_setuptools()
      File "C:\Users\henri\AppData\Local\Temp\pip-install-vf6fwa3c\skeleton\distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "C:\Users\henri\AppData\Local\Temp\pip-install-vf6fwa3c\skeleton\distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "C:\Users\henri\AppData\Local\Temp\pip-install-vf6fwa3c\skeleton\distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "c:\python3\lib\urllib\request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "c:\python3\lib\urllib\request.py", line 532, in open
        response = meth(req, response)
      File "c:\python3\lib\urllib\request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "c:\python3\lib\urllib\request.py", line 570, in error
        return self._call_chain(*args)
      File "c:\python3\lib\urllib\request.py", line 504, in _call_chain
        result = func(*args)
      File "c:\python3\lib\urllib\request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
``` 

What this error happen ? 

PS: other pip package work perfectly

**Comment by bbrauzzi** [comment]
I have the same issue. Any suggestions?
